import { useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import { authRepository } from "../repositories/authRepository";
import { storageService } from "../services/storageService";
import type { CartItem } from "../types/marketplace";
import type { Order, Conversation } from "../types/commerce";
import "./CartPage.css";

export default function CartPage(){
 const nav=useNavigate(),user=authRepository.getCurrentUser(); const [cart,setCart]=useState<CartItem[]>(()=>storageService.get<CartItem[]>("app_cart")??[]); const [payment,setPayment]=useState<"efectivo"|"qr">("efectivo"); const [ordered,setOrdered]=useState(false); const total=useMemo(()=>cart.reduce((s,x)=>s+x.product.price*x.quantity,0),[cart]); if(!user)return null;
 const update=(x:CartItem[])=>{setCart(x);storageService.set("app_cart",x)};
 const confirm=()=>{if(!cart.length)return;const orders=storageService.get<Order[]>("app_orders")??[];const conversations=storageService.get<Conversation[]>("app_conversations")??[];const bySeller=new Map<string,CartItem[]>();cart.forEach(x=>bySeller.set(x.product.sellerId,[...(bySeller.get(x.product.sellerId)??[]),x]));let nextOrders=[...orders],nextChats=[...conversations];bySeller.forEach((items,sellerId)=>{const seller=items[0].product.sellerName;const orderId=`order-${Date.now()}-${sellerId}`;nextOrders.push({id:orderId,buyerId:user.id,buyerName:`${user.nombre} ${user.apellido}`,sellerId,sellerName:seller,items,total:items.reduce((s,x)=>s+x.product.price*x.quantity,0),payment,status:"Pendiente",createdAt:new Date().toISOString()});const id=[user.id,sellerId].sort().join("-");if(!nextChats.some(c=>c.id===id))nextChats.push({id,userIds:[user.id,sellerId],userNames:[`${user.nombre} ${user.apellido}`,seller],orderId,productName:items[0].product.name,updatedAt:new Date().toISOString()})});storageService.set("app_orders",nextOrders);storageService.set("app_conversations",nextChats);setOrdered(true);update([])};
 return <main className="cart-page"><header className="cart-header"><button onClick={()=>nav("/")}>TuTiendaModa</button><span>Mi carrito</span></header><section className="cart-content"><div className="cart-items"><button className="back-store" onClick={()=>nav("/")}>← Seguir comprando</button>{cart.length===0?<div className="cart-empty"><h1>{ordered?"¡Pedido enviado al vendedor!":"Tu carrito está vacío"}</h1><p>{ordered?"El pedido aparece en el perfil del vendedor y ya existe un chat entre ambos.":"Agrega una prenda desde la tienda."}</p><button onClick={()=>nav("/")}>EXPLORAR PRENDAS</button></div>:cart.map((item,i)=><article className="cart-item" key={`${item.product.id}-${item.size}`}><div className="cart-item-image">{item.product.images[0]?<img src={item.product.images[0]} alt={item.product.name}/>:<span>Sin imagen</span>}</div><div className="cart-item-info"><p>{item.product.category}</p><h2>{item.product.name}</h2><span>Vendedor: {item.product.sellerName} · Talla: {item.size}</span><strong>Bs {(item.product.price*item.quantity).toFixed(2)}</strong><div className="quantity"><button onClick={()=>update(cart.map((x,j)=>j===i?{...x,quantity:Math.max(1,x.quantity-1)}:x))}>−</button><span>{item.quantity}</span><button onClick={()=>update(cart.map((x,j)=>j===i?{...x,quantity:x.quantity+1}:x))}>+</button></div><button className="remove" onClick={()=>update(cart.filter((_,j)=>j!==i))}>Eliminar</button></div></article>)}</div>{cart.length>0&&<aside className="checkout"><h2>Resumen</h2><div><span>Subtotal</span><strong>Bs {total.toFixed(2)}</strong></div><div><span>Entrega</span><strong>A coordinar</strong></div><hr/><div className="total"><span>Total</span><strong>Bs {total.toFixed(2)}</strong></div><h3>Método de pago</h3><label className={payment==="efectivo"?"payment selected":"payment"}><input type="radio" checked={payment==="efectivo"} onChange={()=>setPayment("efectivo")}/> 💵 Efectivo</label><label className={payment==="qr"?"payment selected":"payment"}><input type="radio" checked={payment==="qr"} onChange={()=>setPayment("qr")}/> ▣ QR</label>{payment==="qr"&&<div className="qr-box"><strong>Pago por QR</strong><div>▦</div><small>El QR real se conectará al vendedor.</small></div>}<button className="confirm-order" onClick={confirm}>CONFIRMAR PEDIDO</button></aside>}</section></main>}
