import { useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import { authRepository } from "../repositories/authRepository";
import { storageService } from "../services/storageService";
import type { CartItem, Product } from "../types/marketplace";
import type { Order, Conversation } from "../types/commerce";
import "./CartPage.css";

export default function CartPage(){
 const nav=useNavigate(),user=authRepository.getCurrentUser();const[cart,setCart]=useState<CartItem[]>(()=>storageService.get<CartItem[]>("app_cart")??[]),[payment,setPayment]=useState<"efectivo"|"qr">("efectivo"),[ordered,setOrdered]=useState(false),[error,setError]=useState("");const total=useMemo(()=>cart.reduce((s,x)=>s+x.product.price*x.quantity,0),[cart]);if(!user)return null;
 const update=(x:CartItem[])=>{setCart(x);storageService.set("app_cart",x)};
 const changeQty=(index:number,delta:number)=>{const item=cart[index];const products=storageService.get<Product[]>("app_products")??[];const live=products.find(p=>p.id===item.product.id);if(!live)return setError(`La prenda "${item.product.name}" ya no está disponible.`);const nextQty=item.quantity+delta;if(nextQty<1)return; if(nextQty>live.quantity)return setError(`Solo quedan ${live.quantity} unidades de "${live.name}".`);setError("");update(cart.map((x,i)=>i===index?{...x,quantity:nextQty,product:live}:x))};
 const confirm=()=>{if(!cart.length)return;const products=storageService.get<Product[]>("app_products")??[];for(const item of cart){const live=products.find(p=>p.id===item.product.id);if(!live||item.quantity>live.quantity)return setError(!live?`"${item.product.name}" ya no está disponible.`:`Solo quedan ${live.quantity} unidades de "${item.product.name}".`)}const orders=storageService.get<Order[]>("app_orders")??[],conversations=storageService.get<Conversation[]>("app_conversations")??[];const bySeller=new Map<string,CartItem[]>();cart.forEach(x=>bySeller.set(x.product.sellerId,[...(bySeller.get(x.product.sellerId)??[]),x]));let nextOrders=[...orders],nextChats=[...conversations],remaining=[...products];bySeller.forEach((items,sellerId)=>{const seller=items[0].product.sellerName;const orderId=`order-${Date.now()}-${sellerId}`;nextOrders.push({id:orderId,buyerId:user.id,buyerName:`${user.nombre} ${user.apellido}`,sellerId,sellerName:seller,items,total:items.reduce((s,x)=>s+x.product.price*x.quantity,0),payment,status:"Pendiente",createdAt:new Date().toISOString()});const chatId=[user.id,sellerId].sort().join("-");if(!nextChats.some(c=>c.id===chatId))nextChats.push({id:chatId,userIds:[user.id,sellerId],userNames:[`${user.nombre} ${user.apellido}`,seller],orderId,productName:items[0].product.name,updatedAt:new Date().toISOString()})});cart.forEach(item=>{remaining=remaining.map(p=>p.id===item.product.id?{...p,quantity:p.quantity-item.quantity}:p).filter(p=>p.quantity>0)});storageService.set("app_products",remaining);storageService.set("app_orders",nextOrders);storageService.set("app_conversations",nextChats);setError("");setOrdered(true);update([])};
 return <main className="cart-page"><header className="cart-header"><button onClick={()=>nav("/")}>TuTiendaModa</button><span>Mi carrito</span></header><section className="cart-content"><div className="cart-items"><button className="back-store" onClick={()=>nav("/")}>← Seguir comprando</button>{error&&<p className="cart-error">{error}</p>}{cart.length===0?<div className="cart-empty"><h1>{ordered?"¡Pedido enviado al vendedor!":"Tu carrito está vacío"}</h1><p>{ordered?"El pedido aparece en el perfil del vendedor y ya existe un chat entre ambos.":"Agrega una prenda desde la tienda."}</p><button onClick={()=>nav("/")}>EXPLORAR PRENDAS</button></div>:cart.map((item,i)=><article className="cart-item" key={`${item.product.id}-${item.size}`}><div className="cart-item-image">{item.product.images[0]?<img src={item.product.images[0]} alt={item.product.name}/>:<span>Sin imagen</span>}</div><div className="cart-item-info"><p>{item.product.category}</p><h2>{item.product.name}</h2><span>Vendedor: {item.product.sellerName} · Talla: {item.size}</span><small>Disponible: {item.product.quantity} unidad{item.product.quantity===1?"":"es"}</small><strong>Bs {(item.product.price*item.quantity).toFixed(2)}</strong><div className="quantity"><button onClick={()=>changeQty(i,-1)}>−</button><span>{item.quantity}</span><button onClick={()=>changeQty(i,1)}>+</button></div><button className="remove" onClick={()=>update(cart.filter((_,j)=>j!==i))}>Eliminar</button></div></article>)}</div>{cart.length>0&&<aside className="checkout"><h2>Resumen</h2><div><span>Subtotal</span><strong>Bs {total.toFixed(2)}</strong></div><div><span>Entrega</span><strong>A coordinar</strong></div><hr/><div className="total"><span>Total</span><strong>Bs {total.toFixed(2)}</strong></div><h3>Método de pago</h3><label className={payment==="efectivo"?"payment selected":"payment"}><input type="radio" checked={payment==="efectivo"} onChange={()=>setPayment("efectivo")}/> 💵 Efectivo</label><label className={payment==="qr"?"payment selected":"payment"}><input type="radio" checked={payment==="qr"} onChange={()=>setPayment("qr")}/> ▣ QR</label>{payment==="qr"&&<div className="qr-box"><strong>Pago por QR</strong><div>▦</div><small>El QR real se conectará al vendedor.</small></div>}<button className="confirm-order" onClick={confirm}>CONFIRMAR PEDIDO</button></aside>}</section></main>}
