import { useMemo, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { authRepository } from "../repositories/authRepository";
import { storageService } from "../services/storageService";
import type { CartItem, Product } from "../types/marketplace";
import "./ProductDetailPage.css";

const PRODUCTS_KEY="app_products",CART_KEY="app_cart";
export default function ProductDetailPage(){
 const navigate=useNavigate(),{id}=useParams();const products=storageService.get<Product[]>(PRODUCTS_KEY)??[];const product=useMemo(()=>products.find(x=>String(x.id)===id),[products,id]);const[selectedImage,setSelectedImage]=useState(0),[selectedSize,setSelectedSize]=useState(product?.sizes[0]??""),[message,setMessage]=useState("");
 if(!authRepository.isAuthenticated()){navigate("/login",{replace:true});return null} if(!product)return <main className="detail-page"><div className="not-found"><h1>Prenda no encontrada</h1><button onClick={()=>navigate("/")}>VOLVER A LA TIENDA</button></div></main>;
 const addToCart=()=>{if(!selectedSize)return setMessage("Selecciona una talla.");const current=storageService.get<CartItem[]>(CART_KEY)??[];const existing=current.find(x=>x.product.id===product.id&&x.size===selectedSize);const currentQty=existing?.quantity??0;if(currentQty>=product.quantity)return setMessage(`No hay más unidades disponibles. Stock: ${product.quantity}.`);const next=existing?current.map(x=>x.product.id===product.id&&x.size===selectedSize?{...x,quantity:x.quantity+1}:x):[...current,{product,size:selectedSize,quantity:1}];storageService.set(CART_KEY,next);setMessage("¡Prenda agregada al carrito!")};
 const buyNow=()=>{if(product.quantity<1)return setMessage("Esta prenda está agotada.");addToCart();navigate("/carrito")};
 return <main className="detail-page"><header className="detail-header"><button className="detail-brand" onClick={()=>navigate("/")}>TuTiendaModa</button><button className="detail-cart" onClick={()=>navigate("/carrito")}>🛍️ Carrito</button></header><div className="detail-breadcrumb"><button onClick={()=>navigate("/")}>Inicio</button> / {product.category} / {product.name}</div><section className="detail-layout"><div className="gallery"><div className="main-detail-image">{product.images[selectedImage]?<img src={product.images[selectedImage]} alt={product.name}/>:<div>Sin imagen de la prenda</div>}</div>{product.images.length>1&&<div className="thumbnails">{product.images.map((src,i)=><button key={i} className={selectedImage===i?"selected":""} onClick={()=>setSelectedImage(i)}><img src={src} alt={`Vista ${i+1}`}/></button>)}</div>}</div><div className="detail-info"><p className="detail-category">{product.category}</p><h1>{product.name}</h1><div className="detail-price">Bs {product.price.toFixed(2)}</div><div className="detail-divider"/><p><strong>Estado:</strong> {product.status}</p><p><strong>Vendedor:</strong> {product.sellerName}</p><p><strong>Disponibles:</strong> {product.quantity} unidad{product.quantity===1?"":"es"}</p><p className="description">{product.description}</p><h3>Talla</h3><div className="detail-sizes">{product.sizes.map(size=><button key={size} className={selectedSize===size?"selected":""} onClick={()=>setSelectedSize(size)}>{size}</button>)}</div>{message&&<p className="detail-message">{message}</p>}<button className="add-cart" onClick={addToCart} disabled={product.quantity<1}>AGREGAR AL CARRITO</button><button className="buy-now" onClick={buyNow} disabled={product.quantity<1}>COMPRAR AHORA</button><div className="seller-note">Compra segura entre usuarios · Pago disponible en efectivo o QR.</div></div></section></main>;
}
