import { Navigate, useNavigate } from "react-router-dom";
import { authRepository } from "../repositories/authRepository";
import { storageService } from "../services/storageService";
import type { Order } from "../types/commerce";
import type { Product } from "../types/marketplace";
import "./ProfilePage.css";

export default function ProfilePage(){
 const navigate=useNavigate(),user=authRepository.getCurrentUser();if(!user)return <Navigate to="/login" replace/>;const orders=storageService.get<Order[]>("app_orders")??[],products=storageService.get<Product[]>("app_products")??[],sales=orders.filter(o=>o.sellerId===user.id),purchases=orders.filter(o=>o.buyerId===user.id),myProducts=products.filter(p=>p.sellerId===user.id);const logout=()=>{authRepository.logout();navigate("/login",{replace:true})};const deleteProduct=(id:number)=>{if(!window.confirm("¿Eliminar esta publicación? Ya no aparecerá en la tienda."))return;storageService.set("app_products",products.filter(p=>p.id!==id));window.location.reload()};
 const cancelOrder=(orderId:string)=>{const currentOrders=storageService.get<Order[]>("app_orders")??[];const order=currentOrders.find(o=>o.id===orderId);if(!order||order.status==="Cancelado")return;if(!window.confirm("¿Cancelar este pedido? La cantidad comprada volverá a estar disponible y la prenda se publicará nuevamente si se agotó."))return;const currentProducts=storageService.get<Product[]>("app_products")??[];let restored=[...currentProducts];order.items.forEach(item=>{const index=restored.findIndex(p=>p.id===item.product.id);if(index>=0){restored[index]={...restored[index],quantity:restored[index].quantity+item.quantity};}else{restored.push({...item.product,quantity:item.quantity});}});storageService.set("app_products",restored);storageService.set("app_orders",currentOrders.map(o=>o.id===orderId?{...o,status:"Cancelado"}:o));window.location.reload()};
 return <main className="profile-page"><header className="profile-header"><button className="profile-brand" onClick={()=>navigate("/")}>TuTiendaModa</button><button onClick={()=>navigate("/")}>← Volver</button></header><section className="profile-card"><div className="avatar">{user.nombre.charAt(0).toUpperCase()}</div><div><p>MI PERFIL</p><h1>{user.nombre} {user.apellido}</h1><span>{user.email}</span><span>{user.telefono} · {user.departamento ? `${user.departamento} · ` : ""}{user.direccion}</span></div><button className="logout" onClick={logout}>Cerrar sesión</button></section><div className="profile-stats"><div><strong>{myProducts.length}</strong><span>Prendas publicadas</span></div><div><strong>{purchases.length}</strong><span>Compras</span></div><div><strong>{sales.length}</strong><span>Ventas recibidas</span></div></div><section className="profile-orders"><div><h2>Mis publicaciones</h2>{myProducts.length?myProducts.map(p=><article key={p.id}><b>{p.name}</b><span>Bs {p.price.toFixed(2)} · {p.status}</span><small>{p.quantity} unidad{p.quantity===1?"":"es"} disponibles</small><button onClick={()=>navigate(`/producto/${p.id}`)}>Ver prenda</button><button onClick={()=>deleteProduct(p.id)}>🗑️ Eliminar publicación</button></article>):<p>No tienes prendas publicadas.</p>}</div><div><h2>Mis compras</h2>{purchases.length?purchases.map(o=><article key={o.id}><b>Pedido #{o.id.slice(-6)}</b><span>{o.sellerName} · Bs {o.total.toFixed(2)}</span><small>{o.status} · {o.payment==="qr"?"QR":"Efectivo"}</small><button onClick={()=>navigate(`/chat/${o.sellerId}`)}>💬 Hablar con vendedor</button>{o.status!=="Cancelado"&&<button className="cancel-order" onClick={()=>cancelOrder(o.id)}>✕ Cancelar pedido</button>}</article>):<p>Aún no tienes compras.</p>}</div><div><h2>Ventas recibidas</h2>{sales.length?sales.map(o=><article key={o.id}><b>Pedido #{o.id.slice(-6)}</b><span>{o.buyerName} · Bs {o.total.toFixed(2)}</span><small>{o.status} · {o.payment==="qr"?"QR":"Efectivo"}</small><button onClick={()=>navigate(`/chat/${o.buyerId}`)}>💬 Hablar con comprador</button></article>):<p>Aún no tienes ventas.</p>}</div></section></main>;
}
