import { useState } from "react";
import { Navigate, useNavigate } from "react-router-dom";
import type { ChangeEvent, FormEvent } from "react";
import { authRepository } from "../repositories/authRepository";
import { storageService } from "../services/storageService";
import type { Product } from "../types/marketplace";
import "./PublishProductPage.css";

const toDataUrl=(file:File)=>new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result));r.onerror=reject;r.readAsDataURL(file)});
export default function PublishProductPage(){
 const nav=useNavigate(),user=authRepository.getCurrentUser(); const [name,setName]=useState(""),[category,setCategory]=useState<Product["category"]>("Mujer"),[price,setPrice]=useState(""),[status,setStatus]=useState<Product["status"]>("Nuevo"),[sizes,setSizes]=useState(["M"]),[description,setDescription]=useState(""),[images,setImages]=useState<string[]>([]),[message,setMessage]=useState("");
 if(!user)return <Navigate to="/login" replace/>;
 const files=async(e:ChangeEvent<HTMLInputElement>)=>{const f=Array.from(e.target.files??[]);if(f.length)setImages(await Promise.all(f.map(toDataUrl)))};
 const toggle=(s:string)=>setSizes(v=>v.includes(s)?v.filter(x=>x!==s):[...v,s]);
 const submit=(e:FormEvent)=>{e.preventDefault();if(!name.trim()||Number(price)<=0||!sizes.length)return setMessage("Completa nombre, precio y talla.");const p:Product={id:Date.now(),sellerId:user.id,sellerName:`${user.nombre} ${user.apellido}`,name:name.trim(),category,price:Number(price),status,sizes,description:description.trim()||"Prenda publicada en TuTiendaModa.",images,createdAt:new Date().toISOString()};storageService.set("app_products",[p,...(storageService.get<Product[]>("app_products")??[])]);setMessage("¡Prenda publicada!");setTimeout(()=>nav(`/producto/${p.id}`),400)};
 return <main className="publish-page"><header><button onClick={()=>nav("/")}>TuTiendaModa</button><span>Publicar prenda</span></header><form className="publish-card" onSubmit={submit}><div className="publish-heading"><p>VENDE EN TU TIENDAMODA</p><h1>Publica tu prenda</h1><span>Agrega fotos, precio, estado y tallas.</span></div><div className="publish-grid"><label>Nombre<input value={name} onChange={e=>setName(e.target.value)} required/></label><label>Categoría<select value={category} onChange={e=>setCategory(e.target.value as Product["category"])}><option>Mujer</option><option>Hombre</option><option>Niños</option><option>Accesorios</option></select></label><label>Precio (Bs)<input type="number" min="1" value={price} onChange={e=>setPrice(e.target.value)} required/></label><label>Estado<select value={status} onChange={e=>setStatus(e.target.value as Product["status"])}><option>Nuevo</option><option>Usado</option></select></label><fieldset><legend>Tallas</legend><div>{["XS","S","M","L","XL","Única"].map(s=><button type="button" className={sizes.includes(s)?"selected":""} onClick={()=>toggle(s)} key={s}>{s}</button>)}</div></fieldset><label className="wide">Descripción<textarea rows={4} value={description} onChange={e=>setDescription(e.target.value)}/></label><label className="wide">Fotos<input type="file" accept="image/*" multiple onChange={files}/><small>Sube fotos reales de la prenda.</small></label>{images.length>0&&<div className="previews wide">{images.map((x,i)=><img src={x} alt={`Vista ${i+1}`} key={i}/>)}</div>}{message&&<p className="message wide">{message}</p>}<button className="submit wide" type="submit">PUBLICAR PRENDA</button></div></form></main>;
}
